# Generated by Django 5.2.4 on 2025-07-13 15:58

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('ssh_username', models.CharField(max_length=50)),
                ('ssh_password', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
    ]
