# Generated by Django 5.2.5 on 2025-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Router', '0002_router_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='policies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
