# Generated by Django 5.2.5 on 2025-08-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Router', '0003_router_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollbackDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('movement', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
